// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Activity struct {
	ID                 int64           `json:"id"`
	Name               string          `json:"name"`
	Distance           sql.NullFloat64 `json:"distance"`
	MovingTime         sql.NullInt64   `json:"moving_time"`
	ElapsedTime        sql.NullInt64   `json:"elapsed_time"`
	TotalElevationGain sql.NullFloat64 `json:"total_elevation_gain"`
	Type               sql.NullString  `json:"type"`
	SportType          sql.NullString  `json:"sport_type"`
	StartDate          sql.NullTime    `json:"start_date"`
	StartDateLocal     sql.NullTime    `json:"start_date_local"`
	Timezone           sql.NullString  `json:"timezone"`
	AverageSpeed       sql.NullFloat64 `json:"average_speed"`
	MaxSpeed           sql.NullFloat64 `json:"max_speed"`
	AverageCadence     sql.NullFloat64 `json:"average_cadence"`
	AverageHeartrate   sql.NullFloat64 `json:"average_heartrate"`
	MaxHeartrate       sql.NullFloat64 `json:"max_heartrate"`
	Calories           sql.NullFloat64 `json:"calories"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
}

type ActivityZone struct {
	ID          int64        `json:"id"`
	ActivityID  int64        `json:"activity_id"`
	ZoneType    string       `json:"zone_type"`
	SensorBased int64        `json:"sensor_based"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type AuthConfig struct {
	ID           int64          `json:"id"`
	ClientID     string         `json:"client_id"`
	ClientSecret string         `json:"client_secret"`
	AccessToken  sql.NullString `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ZoneBucket struct {
	ID             int64 `json:"id"`
	ActivityZoneID int64 `json:"activity_zone_id"`
	ZoneNumber     int64 `json:"zone_number"`
	MinValue       int64 `json:"min_value"`
	MaxValue       int64 `json:"max_value"`
	TimeSeconds    int64 `json:"time_seconds"`
}
